### ISSUE TITLE
can't run trans 

### ISSUE THREAD

**Issue by laohumultimedia** [xmar/360Transformations#13]
when i run trans with command  ./trans -c ../, always face this error:
Error while parsing the Global.layoutFlow: No such node (Global.layoutFlow)
i use the default config.ini, doesn't change the layout flow, and i also have a Equirectangular video named tOffCopy.mp4  the path.
what's wrong?

**Comment by xmar** [comment]
Hi, the command should be "./trans -c ../config.ini" instead of "./trans -c ../".
The exception you get means that the software wasn't able to find the node layoutFlow in the section Global of the ini file. It seams you gave a path to a folder instead of a path to a ini file.

**Comment by laohumultimedia** [comment]
Thanks xmar, solved now.  And i noticed the default config file missing some items, should add it according to README
