### ISSUE TITLE
Issue with MS-SSIM function in your code

### ISSUE THREAD

**Issue by phunm211** [xmar/360Transformations#17]
I think that there is a problem with your MS-SSIM function in file Picture.cpp (line 271)

> //overall_mssim = prod(mcs_array(1:level-1).^weight(1:level-1))*mssim_array(level);
double msssim = mssim[m_nlevs-1];
for (int l=0; l<m_nlevs-1; l++)
{
msssim *= pow(mcs[l], m_mssimWeight[l]);
}
return msssim;

According to the paper "MULTI-SCALE STRUCTURAL SIMILARITY FOR IMAGE QUALITY ASSESSMENT" of Zhou Wang, the true formula of MS-SSIM is
![image](https://cloud.githubusercontent.com/assets/19267057/24613113/7d6d810e-18b1-11e7-9ab9-185c1418f8e5.png)
So I think that in line 272 of your code, it should be

> double msssim = mssim[m_nlevs-1] * m_mssimWeight[m_nlevs-1];

**Comment by phunm211** [comment]
Sorry, I type wrong. It should be

double msssim = pow(mssim[m_nlevs-1] ,m_mssimWeight[m_nlevs-1]);

**Comment by xmar** [comment]
Thanks for openning this issue.
I applied your fix.
