### ISSUE TITLE
Add support to HEVC

### ISSUE THREAD

**Issue by xmar** [xmar/360Transformations#2]
Add support to HEVC. I might be needed to use the libav.

**Comment by xmar** [comment]
Done

**Comment by qmphobby** [comment]
Can I use this tool in windows？Thank you

**Comment by xmar** [comment]
Hi.
We performed all our tests on linux machines (debian, ubuntu, archlinux) and so we do not claim to support any other OS.
One of the contributor managed to compile and run a previous version of the software on windows. If you update the CMakeLists.txt files or if you configure yourself the compilation chain, it might still be possible to compile it and run it on windows. You have to check you have a modern compiler that support C++11.
If you manage to make it run on a windows machine please let me now it.

**Comment by qmphobby** [comment]
I want to  try  it on windows. If successful , I will notify you.I am very happy to do something for this work.Thank you very much.
