### ISSUE TITLE
Add possibility to do rotation of the 3D cube + the 3D rhombicDodeca

### ISSUE THREAD

**Issue by xmar** [xmar/360Transformations#3]

**Comment by xmar** [comment]
Done

**Comment by qmphobby** [comment]
Hi,can you tell me the ffmpeg's version in this project?

**Comment by xmar** [comment]
Please do not ask questions in closed issues.
On my current pc I have:
gcc version 6.1.1
boost version 1.60.0
ffmpeg version 3.1.3
libavutil version 55.28.100
libavformat  version 57.41.100
libavcodec version 57.48.101
libswscale version 4.1.100
